package com.thinkauth.thinkfusionauth.exceptions

class ResourceNotFoundException():RuntimeException() {

}